theme = "skeria"

# All parameters below here are optional and can be mixed and matched.
[params]
# Used when a given page doesn't set its own.
defaultDescription = "Interesting content."
defaultKeywords = "Interesting keywords."

# Displays under the title, keep it short. You can use markdown here.
tagline = "May the sapphire star light your wayâœ¨"

# Navbar social links, these must be full URLs.
github = "https://github.com/peromage"
bitbucket = ""
stackOverflow = ""
linkedin = "https://www.linkedin.com/in/fangdeng/"
googleplus = ""
facebook = ""
twitter = ""
youtube = ""
orcid = ""
flattr = ""

# Mailto link.
email = "mailto:fang@saffyyre.com"

# GPG key.
gpgkey = "/gpg-pubkey.txt"

# RSS.
rss = false

# Privacy statement link.
privacyNotice = "/privacy"

[menu]
[[menu.main]]
identifier = "categories"
name  = "Categories"
url = "/categories"
weight = 1

[[menu.main]]
identifier = "tags"
name  = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
identifier = "about"
name  = "About"
url = "/about"
weight = 0

[[menu.main]]
identifier = "search"
name  = "Search"
url = "/search"
weight = 4
